sudo: false
dist: trusty
language: php
notifications:
  email:
    on_success: never
    on_failure: change
branches:
  only:
  - master
  - "/^v?[0-9\\.]+/"
cache:
  directories:
  - "$HOME/.composer/cache"
matrix:
  include:
  - php: 7.2
    env: WP_VERSION=latest
  - php: 7.1
    env: WP_VERSION=latest
  - php: 7.0
    env: WP_VERSION=latest
  - php: 7.2
    env: WP_VERSION=nightly
  - php: 7.1
    env: WP_VERSION=nightl
  - php: 7.0
    env: WP_VERSION=nightl
before_script:
- npm install
- npm run build
- export PATH="$HOME/.composer/vendor/bin:$PATH"
- composer install
- bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
- composer global require "phpunit/phpunit=4.8.*|5.7.*"
script:
- phpunit
after_success:
- sed -i -e "s/nightly/${TRAVIS_TAG}/" _shops.php
- npm install && npm run build
- curl https://raw.githubusercontent.com/miya0001/auto-build/master/auto-build.sh
  | bash
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: thyBvT7HaF72mJDXZn015MLCJr6dKnS9+w02AN4iSRnDpKu6UgHfHfsX+jJe/NrceIfzTwNQYOXyrxfZyrlZsmodgUPtlmdEO2Ctu5Q3+xKA6ilvgnsqQoIWlkPRzVSLTwkWteUo1mQfJG0CB78udKI4KgxAm/NpaSIZRiSSwtmC668mjP7vVQHpHg3SJI1IgR9/BqmrDBHwT1CpKXgg2Owk5M8hb2oOiSvbHoZspkWfjNPrjoEkO6aHnhnFSRwPtsS/nZLfL6LEvMuXm2pqyIMrnRQuL888fewSmyfn45eFV8htXcQGhIUFV8GK5HTfF+z5m+mzsjTbbvaKtnGaQPJS5QN0WK6BMr77OMqDdd2RRABJNgrbU7B/n2vHq+smtlzGtzL/4gLb2y/QWgQjLZWp6aqEopg4giILBrqHweARn/zmoDVjnThoCuIdnZUPPH/JlZbPWC/nmf1YpquwmHWv3+1pSy2xWfMSYRcjDtXwioGddCGD6wLo0uVX1E6sYMpoWLumrxsEds1NMjgpM1yLnPBYXvXNstFGtRL391fq8dUkXiIUlNzLlILaBFab5RQkXFx5rK6LTuIL2AtMht2IoX4TxXSj+8NBNZoHHLJq5uJo28pE+xnqFTZ7taAvPGI5jVK/j5p1niNXl+Gv8bS8b4xlpk3HRZsg+TN4JEY=
  file: '_shops.zip'
  on:
    tags: true
    repo: miya0001/_shops
